from django.db import models

class TickerPesquisa(models.Model):
    TICKER = models.CharField(max_length=10)
    DENOM_SOCIAL = models.CharField(max_length=50)
    ISIN = models.CharField(max_length=20, blank=True, null=True)
    
    def __str__(self):
        return self.TICKER

class InformeDiario(models.Model):
    TP_FUNDO = models.CharField(max_length=20)
    CNPJ_FUNDO = models.CharField(max_length=20)
    DT_COMPTC = models.DateField(null=True, blank=True)
    VL_TOTAL = models.FloatField()
    VL_QUOTA = models.FloatField()
    VL_PATRIM_LIQ = models.FloatField()
    CAPTC_DIA = models.FloatField()
    RESG_DIA = models.FloatField()
    NR_COTST = models.FloatField()

    class Meta:
        indexes = [
            models.Index(fields=['CNPJ_FUNDO']),
        ]

    def __str__(self):
        return self.CNPJ_FUNDO

class CadFi(models.Model):
    TP_FUNDO = models.CharField(max_length=100)
    CNPJ_FUNDO = models.CharField(max_length=100)
    DENOM_SOCIAL = models.CharField(max_length=1000)
    DT_REG = models.DateField(null=True, blank=True)
    DT_CONST = models.DateField(null=True, blank=True)
    CD_CVM = models.CharField(max_length=20, null=True, blank=True)
    DT_CANCEL = models.DateField(null=True, blank=True)
    SIT = models.CharField(max_length=100, null=True, blank=True)
    DT_INI_SIT = models.DateField(null=True, blank=True)
    DT_INI_ATIV = models.DateField(null=True, blank=True)
    DT_INI_EXERC = models.DateField(null=True, blank=True)
    DT_FIM_EXERC = models.DateField(null=True, blank=True)
    CLASSE = models.CharField(max_length=100, null=True, blank=True)
    DT_INI_CLASSE = models.DateField(null=True, blank=True)
    RENTAB_FUNDO = models.CharField(max_length=100, null=True, blank=True)
    CONDOM = models.CharField(max_length=100, null=True, blank=True)
    FUNDO_COTAS = models.CharField(max_length=100, null=True, blank=True)
    FUNDO_EXCLUSIVO = models.CharField(max_length=100, null=True, blank=True)
    TRIB_LPRAZO = models.CharField(max_length=100, null=True, blank=True)
    PUBLICO_ALVO = models.CharField(max_length=100, null=True, blank=True)
    ENTID_INVEST = models.CharField(max_length=100, null=True, blank=True)
    TAXA_PERFM = models.CharField(max_length=100, null=True, blank=True)
    INF_TAXA_PERFM = models.CharField(max_length=1000000, null=True, blank=True)
    TAXA_ADM = models.CharField(max_length=100, null=True, blank=True)
    INF_TAXA_ADM = models.CharField(max_length=1000000, null=True, blank=True)
    VL_PATRIM_LIQ = models.CharField(max_length=100, null=True, blank=True)
    DT_PATRIM_LIQ = models.DateField(null=True, blank=True)
    DIRETOR = models.CharField(max_length=100, null=True, blank=True)
    CNPJ_ADMIN = models.CharField(max_length=100, null=True, blank=True)
    ADMIN = models.CharField(max_length=100, null=True, blank=True)
    PF_PJ_GESTOR = models.CharField(max_length=100, null=True, blank=True)
    CPF_CNPJ_GESTOR = models.CharField(max_length=100, null=True, blank=True)
    GESTOR = models.CharField(max_length=100, null=True, blank=True)
    CNPJ_AUDITOR = models.CharField(max_length=100, null=True, blank=True)
    AUDITOR = models.CharField(max_length=100, null=True, blank=True)
    CNPJ_CUSTODIANTE = models.CharField(max_length=100, null=True, blank=True)
    CUSTODIANTE = models.CharField(max_length=100, null=True, blank=True)
    CNPJ_CONTROLADOR = models.CharField(max_length=100, null=True, blank=True)
    CONTROLADOR = models.CharField(max_length=100, null=True, blank=True)
    INVEST_CEMPR_EXTER = models.CharField(max_length=100, null=True, blank=True)
    CLASSE_ANBIMA = models.CharField(max_length=100, null=True, blank=True)

class ExtratoFi(models.Model):
    CNPJ_FUNDO = models.CharField(max_length=100)
    DENOM_SOCIAL = models.CharField(max_length=100)
    DT_COMPTC = models.CharField(max_length=100, null=True, blank=True)
    CONDOM = models.CharField(max_length=100, null=True, blank=True)
    NEGOC_MERC = models.CharField(max_length=100, null=True, blank=True)
    MERCADO = models.CharField(max_length=100, null=True, blank=True)
    TP_PRAZO = models.CharField(max_length=100, null=True, blank=True)
    PRAZO = models.CharField(max_length=100, null=True, blank=True)
    PUBLICO_ALVO = models.CharField(max_length=100, null=True, blank=True)
    REG_ANBIMA = models.CharField(max_length=100, null=True, blank=True)
    CLASSE_ANBIMA = models.CharField(max_length=100, null=True, blank=True)
    DISTRIB = models.CharField(max_length=100, null=True, blank=True)
    POLIT_INVEST = models.CharField(max_length=100, null=True, blank=True)
    APLIC_MAX_FUNDO_LIGADO = models.CharField(max_length=100, null=True, blank=True)
    RESULT_CART_INCORP_PL = models.CharField(max_length=100, null=True, blank=True)
    FUNDO_COTAS = models.CharField(max_length=100, null=True, blank=True)
    FUNDO_ESPELHO = models.CharField(max_length=100, null=True, blank=True)
    APLIC_MIN = models.CharField(max_length=100, null=True, blank=True)
    ATUALIZ_DIARIA_COTA = models.CharField(max_length=100, null=True, blank=True)
    PRAZO_ATUALIZ_COTA = models.CharField(max_length=100, null=True, blank=True)
    COTA_EMISSAO = models.CharField(max_length=100, null=True, blank=True)
    COTA_PL = models.CharField(max_length=100, null=True, blank=True)
    QT_DIA_CONVERSAO_COTA = models.CharField(max_length=100, null=True, blank=True)
    QT_DIA_PAGTO_COTA = models.CharField(max_length=100, null=True, blank=True)
    QT_DIA_RESGATE_COTAS = models.CharField(max_length=100, null=True, blank=True)
    QT_DIA_PAGTO_RESGATE = models.CharField(max_length=100, null=True, blank=True)
    TP_DIA_PAGTO_RESGATE = models.CharField(max_length=100, null=True, blank=True)
    TAXA_SAIDA_PAGTO_RESGATE = models.CharField(max_length=100, null=True, blank=True)
    TAXA_ADM = models.CharField(max_length=100, null=True, blank=True)
    TAXA_CUSTODIA_MAX = models.CharField(max_length=100, null=True, blank=True)
    EXISTE_TAXA_PERFM = models.CharField(max_length=100, null=True, blank=True)
    TAXA_PERFM = models.CharField(max_length=100, null=True, blank=True)
    PARAM_TAXA_PERFM = models.CharField(max_length=100, null=True, blank=True)
    PR_INDICE_REFER_TAXA_PERFM = models.CharField(max_length=100, null=True, blank=True)
    VL_CUPOM = models.CharField(max_length=100, null=True, blank=True)
    CALC_TAXA_PERFM = models.CharField(max_length=100, null=True, blank=True)
    INF_TAXA_PERFM = models.CharField(max_length=100, null=True, blank=True)
    EXISTE_TAXA_INGRESSO = models.CharField(max_length=100, null=True, blank=True)
    TAXA_INGRESSO_REAL = models.CharField(max_length=100, null=True, blank=True)
    TAXA_INGRESSO_PR = models.CharField(max_length=100, null=True, blank=True)
    EXISTE_TAXA_SAIDA = models.CharField(max_length=100, null=True, blank=True)
    TAXA_SAIDA_REAL = models.CharField(max_length=100, null=True, blank=True)
    TAXA_SAIDA_PR = models.CharField(max_length=100, null=True, blank=True)
    OPER_DERIV = models.CharField(max_length=100, null=True, blank=True)
    FINALIDADE_OPER_DERIV = models.CharField(max_length=100, null=True, blank=True)
    OPER_VL_SUPERIOR_PL = models.CharField(max_length=100, null=True, blank=True)
    FATOR_OPER_VL_SUPERIOR_PL = models.CharField(max_length=100, null=True, blank=True)
    CONTRAP_LIGADO = models.CharField(max_length=100, null=True, blank=True)
    INVEST_EXTERIOR = models.CharField(max_length=100, null=True, blank=True)
    APLIC_MAX_ATIVO_EXTERIOR = models.CharField(max_length=100, null=True, blank=True)
    ATIVO_CRED_PRIV = models.CharField(max_length=100, null=True, blank=True)
    APLIC_MAX_ATIVO_CRED_PRIV = models.CharField(max_length=100, null=True, blank=True)
    PR_INSTITUICAO_FINANC_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_INSTITUICAO_FINANC_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_CIA_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_CIA_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_FI_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_FI_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_UNIAO_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_UNIAO_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_ADMIN_GESTOR_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_ADMIN_GESTOR_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_EMISSOR_OUTRO_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_EMISSOR_OUTRO_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FI_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FI_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FIC_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FIC_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FI_QUALIF_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FI_QUALIF_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FIC_QUALIF_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FIC_QUALIF_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FI_PROF_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FI_PROF_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FIC_PROF_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FIC_PROF_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FII_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FII_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FIDC_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FIDC_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FICFIDC_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FICFIDC_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FIDC_NP_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FIDC_NP_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FICFIDC_NP_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FICFIDC_NP_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_ETF_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_ETF_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_CRI_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_CRI_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_TITPUB_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_TITPUB_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_OURO_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_OURO_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_TIT_INSTITUICAO_FINANC_BACEN_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_TIT_INSTITUICAO_FINANC_BACEN_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_VLMOB_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_VLMOB_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_ACAO_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_ACAO_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_DEBENTURE_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_DEBENTURE_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_NP_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_NP_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COMPROM_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COMPROM_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_DERIV_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_DERIV_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_ATIVO_OUTRO_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_ATIVO_OUTRO_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FMIEE_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FMIEE_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FIP_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FIP_MAX = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FICFIP_MIN = models.CharField(max_length=100, null=True, blank=True)
    PR_COTA_FICFIP_MAX = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.DENOM_SOCIAL

