# Generated by Django 5.0.6 on 2024-05-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeuModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TP_FUNDO', models.CharField(max_length=100)),
                ('CNPJ_FUNDO', models.CharField(max_length=20)),
                ('DT_COMPTC', models.DateField()),
                ('VL_TOTAL', models.CharField(max_length=50)),
                ('VL_QUOTA', models.CharField(max_length=50)),
                ('VL_PATRIM_LIQ', models.CharField(max_length=50)),
                ('CAPTC_DIA', models.CharField(max_length=50)),
                ('RESG_DIA', models.CharField(max_length=50)),
                ('NR_COTST', models.CharField(max_length=20)),
            ],
        ),
    ]
