# Generated by Django 5.0.6 on 2024-05-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeuModelo',
            new_name='Fundos',
        ),
    ]
