# Generated by Django 5.0.6 on 2024-05-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0003_extratofi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fundos',
            new_name='InformeDiario',
        ),
    ]
