# Generated by Django 5.0.6 on 2024-05-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0004_rename_fundos_informediario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadFi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TP_FUNDO', models.CharField(max_length=100)),
                ('CNPJ_FUNDO', models.CharField(max_length=100)),
                ('DENOM_SOCIAL', models.CharField(max_length=100)),
                ('DT_REG', models.DateField(blank=True, null=True)),
                ('DT_CONST', models.DateField(blank=True, null=True)),
                ('CD_CVM', models.CharField(max_length=20)),
                ('DT_CANCEL', models.DateField(blank=True, null=True)),
                ('SIT', models.CharField(max_length=100)),
                ('DT_INI_SIT', models.DateField(blank=True, null=True)),
                ('DT_INI_ATIV', models.DateField(blank=True, null=True)),
                ('DT_INI_EXERC', models.DateField(blank=True, null=True)),
                ('DT_FIM_EXERC', models.DateField(blank=True, null=True)),
                ('CLASSE', models.CharField(max_length=100)),
                ('DT_INI_CLASSE', models.DateField(blank=True, null=True)),
                ('RENTAB_FUNDO', models.CharField(max_length=100)),
                ('CONDOM', models.CharField(max_length=100)),
                ('FUNDO_COTAS', models.CharField(max_length=100)),
                ('FUNDO_EXCLUSIVO', models.CharField(max_length=100)),
                ('TRIB_LPRAZO', models.CharField(max_length=100)),
                ('PUBLICO_ALVO', models.CharField(max_length=100)),
                ('ENTID_INVEST', models.CharField(max_length=100)),
                ('TAXA_PERFM', models.CharField(max_length=100)),
                ('INF_TAXA_PERFM', models.CharField(max_length=100)),
                ('TAXA_ADM', models.CharField(max_length=100)),
                ('INF_TAXA_ADM', models.CharField(max_length=100)),
                ('VL_PATRIM_LIQ', models.CharField(max_length=100)),
                ('DT_PATRIM_LIQ', models.DateField(blank=True, null=True)),
                ('DIRETOR', models.CharField(max_length=100)),
                ('CNPJ_ADMIN', models.CharField(max_length=100)),
                ('ADMIN', models.CharField(max_length=100)),
                ('PF_PJ_GESTOR', models.CharField(max_length=100)),
                ('CPF_CNPJ_GESTOR', models.CharField(max_length=100)),
                ('GESTOR', models.CharField(max_length=100)),
                ('CNPJ_AUDITOR', models.CharField(max_length=100)),
                ('AUDITOR', models.CharField(max_length=100)),
                ('CNPJ_CUSTODIANTE', models.CharField(max_length=100)),
                ('CUSTODIANTE', models.CharField(max_length=100)),
                ('CNPJ_CONTROLADOR', models.CharField(max_length=100)),
                ('CONTROLADOR', models.CharField(max_length=100)),
                ('INVEST_CEMPR_EXTER', models.CharField(max_length=100)),
                ('CLASSE_ANBIMA', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='informediario',
            name='CAPTC_DIA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='DT_COMPTC',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='NR_COTST',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='RESG_DIA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='TP_FUNDO',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='VL_PATRIM_LIQ',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='VL_QUOTA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='VL_TOTAL',
            field=models.FloatField(),
        ),
    ]
