# Generated by Django 5.0.6 on 2024-05-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0005_cadfi_alter_informediario_captc_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadfi',
            name='ADMIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='AUDITOR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='CD_CVM',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='CLASSE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='CLASSE_ANBIMA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='CNPJ_ADMIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='CNPJ_AUDITOR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='CNPJ_CONTROLADOR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='CNPJ_CUSTODIANTE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='CONDOM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='CONTROLADOR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='CPF_CNPJ_GESTOR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='CUSTODIANTE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='DIRETOR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='ENTID_INVEST',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='FUNDO_COTAS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='FUNDO_EXCLUSIVO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='GESTOR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='INF_TAXA_ADM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='INF_TAXA_PERFM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='INVEST_CEMPR_EXTER',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='PF_PJ_GESTOR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='PUBLICO_ALVO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='RENTAB_FUNDO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='SIT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='TAXA_ADM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='TAXA_PERFM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='TRIB_LPRAZO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='VL_PATRIM_LIQ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='APLIC_MAX_ATIVO_CRED_PRIV',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='APLIC_MAX_ATIVO_EXTERIOR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='APLIC_MAX_FUNDO_LIGADO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='APLIC_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='ATIVO_CRED_PRIV',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='ATUALIZ_DIARIA_COTA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='CALC_TAXA_PERFM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='CLASSE_ANBIMA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='CONDOM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='CONTRAP_LIGADO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='COTA_EMISSAO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='COTA_PL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='DISTRIB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='DT_COMPTC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='EXISTE_TAXA_INGRESSO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='EXISTE_TAXA_PERFM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='EXISTE_TAXA_SAIDA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='FATOR_OPER_VL_SUPERIOR_PL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='FINALIDADE_OPER_DERIV',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='FUNDO_COTAS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='FUNDO_ESPELHO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='INF_TAXA_PERFM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='INVEST_EXTERIOR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='MERCADO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='NEGOC_MERC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='OPER_DERIV',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='OPER_VL_SUPERIOR_PL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PARAM_TAXA_PERFM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='POLIT_INVEST',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PRAZO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PRAZO_ATUALIZ_COTA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_ACAO_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_ACAO_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_ADMIN_GESTOR_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_ADMIN_GESTOR_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_ATIVO_OUTRO_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_ATIVO_OUTRO_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_CIA_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_CIA_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COMPROM_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COMPROM_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_ETF_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_ETF_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FICFIDC_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FICFIDC_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FICFIDC_NP_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FICFIDC_NP_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FICFIP_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FICFIP_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FIC_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FIC_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FIC_PROF_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FIC_PROF_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FIC_QUALIF_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FIC_QUALIF_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FIDC_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FIDC_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FIDC_NP_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FIDC_NP_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FII_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FII_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FIP_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FIP_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FI_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FI_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FI_PROF_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FI_PROF_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FI_QUALIF_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FI_QUALIF_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FMIEE_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_COTA_FMIEE_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_CRI_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_CRI_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_DEBENTURE_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_DEBENTURE_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_DERIV_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_DERIV_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_EMISSOR_OUTRO_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_EMISSOR_OUTRO_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_FI_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_FI_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_INDICE_REFER_TAXA_PERFM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_INSTITUICAO_FINANC_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_INSTITUICAO_FINANC_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_NP_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_NP_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_OURO_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_OURO_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_TITPUB_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_TITPUB_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_TIT_INSTITUICAO_FINANC_BACEN_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_TIT_INSTITUICAO_FINANC_BACEN_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_UNIAO_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_UNIAO_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_VLMOB_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PR_VLMOB_MIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='PUBLICO_ALVO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='QT_DIA_CONVERSAO_COTA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='QT_DIA_PAGTO_COTA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='QT_DIA_PAGTO_RESGATE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='QT_DIA_RESGATE_COTAS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='REG_ANBIMA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='RESULT_CART_INCORP_PL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='TAXA_ADM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='TAXA_CUSTODIA_MAX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='TAXA_INGRESSO_PR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='TAXA_INGRESSO_REAL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='TAXA_PERFM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='TAXA_SAIDA_PAGTO_RESGATE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='TAXA_SAIDA_PR',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='TAXA_SAIDA_REAL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='TP_DIA_PAGTO_RESGATE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='TP_PRAZO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extratofi',
            name='VL_CUPOM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
