# Generated by Django 5.0.6 on 2024-05-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0006_alter_cadfi_admin_alter_cadfi_auditor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadfi',
            name='CNPJ_FUNDO',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
