# Generated by Django 5.0.6 on 2024-05-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0007_alter_cadfi_cnpj_fundo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadfi',
            name='CNPJ_FUNDO',
            field=models.CharField(max_length=100),
        ),
    ]
