# Generated by Django 5.0.6 on 2024-05-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0008_alter_cadfi_cnpj_fundo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informediario',
            name='TP_FUNDO',
            field=models.CharField(max_length=20),
        ),
    ]
