# Generated by Django 5.0.6 on 2024-05-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0010_alter_cadfi_denom_social_alter_cadfi_inf_taxa_adm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadfi',
            name='INF_TAXA_ADM',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='cadfi',
            name='INF_TAXA_PERFM',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
