# Generated by Django 5.0.6 on 2024-05-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0013_alter_cadfi_inf_taxa_adm_alter_cadfi_inf_taxa_perfm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='informediario',
            index=models.Index(fields=['CNPJ_FUNDO'], name='fundos_info_CNPJ_FU_fd82d0_idx'),
        ),
    ]
