# Generated by Django 5.0.6 on 2024-07-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundos', '0014_informediario_fundos_info_cnpj_fu_fd82d0_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TICKER', models.CharField(max_length=10)),
                ('DENOM_SOCIAL', models.CharField(max_length=50)),
            ],
        ),
    ]
